#エレベーターに使うことのできるブロックの登録です - BLOCK_NAME:<距離> のように入力して下さい
elevator:
 - REDSTONE_BLOCK:8
 - LAPIS_BLOCK:16
 - IRON_BLOCK:32
 - EMERALD_BLOCK:64
 - GOLD_BLOCK:128
 - DIAMOND_BLOCK:256

#LoginMessageの設定です
LoginMessage:

#サーバーに入った時に表示されるメッセージを表示します
 LoginMessage: "&e<player>様がログインしました"

#初めてサーバーにログインした時に表示する文字を設定します
 FirstLogin:
  - "&eThanks FirstLogin &r<player>&e!"
  - "&eWelcome to HonobonoServer!"

 #入った時のメッセージの後に表示できるメッセージの設定をします
 Login:
  - Hello! Honobonoserver!
  - Test1!

 #サーバーを出た時に表示されるメッセージを表示します
 LogoutMessage: "&e<player>様がログアウトしました"

#<ItemID>:<meta>:<amount>の順で入力します。また<meta>, <amount>がない場合0, 1が入ります。
LoginBonus:
 - 264
 - 264:1
 - 264:2:1

#サーバーの説明欄をランダムで変更します また\nを入れると改行となります
Motd:
 - "&bTest1!"
 - テスト2!
 - Test3!

#ShowCommandの設定です
ShowCommand:
 prefix: "&b[SC]&r"
 format: "<prefix><player>:<command>"

#アナウンスの設定です
announcement:
  enable: false
  random: false
  prefix: "&d[Announcement]&r"
  interval: 100
  messages:
  - "Test1"
  - "Test2"

Twitter:
  ServerIP: mc.honobono.co

Food:
  - APPLE:1:6